# 1) Start from Golang base image
FROM golang:1.24.5-alpine

# 2) Install dependencies
RUN apk update && apk add --no-cache git build-base

# 3) Set workdir
WORKDIR /app

# 4) Copy source code
COPY docker/socket-server /app/socket-server
COPY .env /app/socket-server/.env

# 5) Go to project dir & download dependencies
WORKDIR /app/socket-server
RUN go mod download

# 6) Run the Go program
RUN go build -o main socket.go
RUN ls -a
CMD ["./main"]
