# Stage 1: Build
FROM golang:tip-alpine3.22 AS build

RUN apk add --no-cache git build-base

WORKDIR /app/socket-server

COPY docker/socket-server/go.mod docker/socket-server/go.sum ./
RUN go mod download

COPY docker/socket-server ./

RUN go build -o main socket.go

# Stage 2: Runtime
FROM golang:tip-alpine3.22

RUN apk add --no-cache ca-certificates

WORKDIR /app/socket-server

COPY --from=build /app/socket-server/main ./
COPY .env ./


CMD ["./main"]
